package com.nicegis.gerhard.model;

import java.io.Serializable;

public class Id implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.id
     *
     * @mbggenerated Tue Dec 17 10:00:52 CST 2019
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.username
     *
     * @mbggenerated Tue Dec 17 10:00:52 CST 2019
     */

    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.id
     *
     * @param id the value for user.id
     *
     * @mbggenerated Tue Dec 17 10:00:52 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

}